# Generated by Django 4.2.7 on 2023-11-17 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "it"),
                            ("HR", "hr"),
                            ("OPERATIONS", "operations"),
                        ],
                        max_length=25,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("doj", models.DateField()),
                ("address", models.CharField(max_length=200)),
                ("contact_number", models.CharField(max_length=20)),
                ("email_id", models.EmailField(max_length=254)),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="LeaveManager.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
