# Generated by Django 4.2.7 on 2023-11-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LeaveManager", "0004_alter_leaveaccruement_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
