# Generated by Django 4.2.7 on 2023-11-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LeaveManager", "0005_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="slug",
            field=models.CharField(default="hdgfjdhfkdf", max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
