# Generated by Django 4.2.7 on 2023-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LeaveManager", "0006_leaverequest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="reason",
            field=models.CharField(default="None", max_length=200),
            preserve_default=False,
        ),
    ]
