# Generated by Django 4.2.7 on 2023-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LeaveManager", "0007_leaverequest_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holidays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="leaveaccruement",
            name="unit",
            field=models.CharField(
                choices=[("MONTH", "month"), ("YEAR", "year")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "approved"),
                    ("REJECTED", "rejected"),
                    ("UNAVAILABLE", "unavailable"),
                ],
                max_length=20,
            ),
        ),
    ]
